### ISSUE TITLE
Logo Suggestions

### ISSUE THREAD

**Issue by Valodim** [katzenpost/docs#11]
So the candidate logo I would like to propose is:

Variant 1:
![cat-logo-mirror svg](https://user-images.githubusercontent.com/27813/35487935-d21f0fbc-0481-11e8-94f2-24e6132ae58d.png)
Variant 2:
![cat-logo-mirror-halfarrow svg](https://user-images.githubusercontent.com/27813/35487936-d23fc414-0481-11e8-8390-4413daa54f53.png)

It was based on this one, adding the "arrow tail" to symbolize a "loop". Moritz said maybe we should just use that one?
![cat-original svg](https://user-images.githubusercontent.com/27813/35488009-b348d1b2-0482-11e8-9fbc-d79496abf36d.png)

I used this as a placeholder at first for the android app, but I pretty much liked it right away. It doesn't have the "snark" of the other logos, but I would consider that a feature, for something that is supposed to represent the project to outsiders.

Either way- feel free to take, leave, or suggest differently.

**Comment by david415** [comment]
WRONG REPO FOR THIS TICKET; see https://github.com/katzenpost/mixnet_uprising/issues/45
