### ISSUE TITLE
Broken links in appendix refs

### ISSUE THREAD

**Issue by leto** [katzenpost/docs#73]
This link is a 404:

[KAETZCHEN] | (1, 2, 3, 4, 5, 6) Angel, Y., Kaneko, K., Stainton, D., "Katzenpost Provider-side Autoresponder", January 2018, <https://github.com/Katzenpost/docs/blob/master/drafts/kaetzchen.rst>.

**Comment by david415** [comment]
which document? that link should be changed to https://github.com/katzenpost/docs/blob/master/specs/kaetzchen.rst

**Comment by leto** [comment]
@david415 link was here: https://github.com/katzenpost/docs/blob/master/drafts/zcash_send.rst which was fixed, closing!

Thanks again for the awesome mixnet bibliography!
